// Auto-generated by scripts/build-content.ts from .snapshot/*.json.
// Edit the source TypeScript directly when authoring new content via Claude-as-CMS.
// Do NOT commit raw snapshot JSON; this file IS the source of truth.

export { activities } from './activities'
export { news } from './news'
export { pages } from './pages'
export { header } from './globals/header'
export { footer } from './globals/footer'
export { siteSettings } from './globals/site-settings'
export { donationSettings } from './globals/donation-settings'
export * from './schema'
export * from './queries'
