/* eslint-disable @typescript-eslint/no-explicit-any */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  Activity,
  NewsArticle,
  Page,
  Header,
  Footer,
  SiteSettings,
  DonationSettings,
  PAGE_SLUGS,
} from '../src/content/schema.js'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')
const SNAPSHOT = join(ROOT, '.snapshot')
const OUT = join(ROOT, 'src', 'content')

const ensureDir = (p: string) => {
  if (!existsSync(p)) mkdirSync(p, { recursive: true })
}
ensureDir(OUT)
ensureDir(join(OUT, 'globals'))

const readJson = (file: string) =>
  JSON.parse(readFileSync(join(SNAPSHOT, file), 'utf-8'))

const stripPayloadMeta = (doc: any): any => {
  const { globalType: _g, ...rest } = doc ?? {}
  return rest
}

const tsHeader = `// Auto-generated by scripts/build-content.ts from .snapshot/*.json.
// Edit the source TypeScript directly when authoring new content via Claude-as-CMS.
// Do NOT commit raw snapshot JSON; this file IS the source of truth.

`

const writeTs = (file: string, body: string) => {
  writeFileSync(join(OUT, file), tsHeader + body + '\n', 'utf-8')
}

const stringify = (v: unknown) => JSON.stringify(v, null, 2)

const processActivities = () => {
  const { docs } = readJson('activities.json')
  const parsed = docs.map((d: any) => Activity.parse(d))
  const body = `import type { Activity } from './schema'

export const activities: Activity[] = ${stringify(parsed)}
`
  writeTs('activities.ts', body)
  return parsed.length
}

const processNews = () => {
  const { docs } = readJson('news.json')
  const parsed = docs.map((d: any) => NewsArticle.parse(d))
  const body = `import type { NewsArticle } from './schema'

export const news: NewsArticle[] = ${stringify(parsed)}
`
  writeTs('news.ts', body)
  return parsed.length
}

const processPages = () => {
  const { docs } = readJson('pages.json')
  const parsed = docs.map((d: any) => Page.parse(d))
  const bySlug: Record<string, unknown> = {}
  for (const p of parsed) bySlug[p.slug as string] = p

  for (const slug of PAGE_SLUGS) {
    if (!bySlug[slug]) {
      throw new Error(`Missing required page slug in snapshot: ${slug}`)
    }
  }

  const body = `import type { Page, PageSlug } from './schema'

const _pages = ${stringify(bySlug)} as const

export const pages: Record<PageSlug, Page> = _pages as unknown as Record<PageSlug, Page>
`
  writeTs('pages.ts', body)
  return parsed.length
}

const processGlobal = <T>(
  fileIn: string,
  schema: { parse: (d: unknown) => T },
  fileOut: string,
  exportName: string,
  typeName: string,
) => {
  const raw = stripPayloadMeta(readJson(fileIn))
  const parsed = schema.parse(raw)
  const body = `import type { ${typeName} } from '../schema'

export const ${exportName}: ${typeName} = ${stringify(parsed)}
`
  writeFileSync(
    join(OUT, 'globals', fileOut),
    tsHeader + body + '\n',
    'utf-8',
  )
}

const main = () => {
  const a = processActivities()
  const n = processNews()
  const p = processPages()
  processGlobal('globals_header.json', Header, 'header.ts', 'header', 'Header')
  processGlobal('globals_footer.json', Footer, 'footer.ts', 'footer', 'Footer')
  processGlobal(
    'globals_site-settings.json',
    SiteSettings,
    'site-settings.ts',
    'siteSettings',
    'SiteSettings',
  )
  processGlobal(
    'globals_donation-settings.json',
    DonationSettings,
    'donation-settings.ts',
    'donationSettings',
    'DonationSettings',
  )

  const indexBody = `export { activities } from './activities'
export { news } from './news'
export { pages } from './pages'
export { header } from './globals/header'
export { footer } from './globals/footer'
export { siteSettings } from './globals/site-settings'
export { donationSettings } from './globals/donation-settings'
export * from './schema'
export * from './queries'
`
  writeTs('index.ts', indexBody.trimEnd())

  // eslint-disable-next-line no-console
  console.log(`✓ activities: ${a}, news: ${n}, pages: ${p}, globals: 4`)
}

main()
