// Auto-generated by scripts/build-content.ts from .snapshot/*.json.
// Edit the source TypeScript directly when authoring new content via Claude-as-CMS.
// Do NOT commit raw snapshot JSON; this file IS the source of truth.

import type { DonationSettings } from '../schema'

export const donationSettings: DonationSettings = {
  "modalTitle": {
    "es": "Hacer una donación",
    "en": "Make a donation"
  },
  "modalDescription": {
    "es": "Elige tu método de donación preferido. Cada contribución nos ayuda a brindar educación, cuidado infantil y programas comunitarios a quienes más lo necesitan.",
    "en": "Choose your preferred donation method below. Every contribution helps us provide education, child care, and community programs to those who need it most."
  },
  "paypal": {
    "enabled": true,
    "link": "https://www.paypal.me/fgrandmothershouse"
  },
  "bankTransfer": {
    "enabled": true,
    "bankName": "Banreservas",
    "accountNumber": "9609143691",
    "accountType": "Checking",
    "accountHolder": "Elizabeth González Hilario - Céd. 023-0140481-6",
    "routingNumber": null,
    "swift": null
  },
  "zelle": {
    "enabled": false,
    "emailOrPhone": "grandmothershousedaycare@gmail.com"
  },
  "otherMethods": []
}

