// Auto-generated by scripts/build-content.ts from .snapshot/*.json.
// Edit the source TypeScript directly when authoring new content via Claude-as-CMS.
// Do NOT commit raw snapshot JSON; this file IS the source of truth.

import type { Footer } from '../schema'

export const footer: Footer = {
  "logo": null,
  "description": {
    "es": "La Fundación Grandmother's House se dedica a proporcionar un entorno seguro, estimulante y cariñoso donde cada niño pueda desarrollarse plenamente. A través de educación, juego creativo y apoyo comunitario, nos esforzamos por ser la luz para aquellos que están en la oscuridad.",
    "en": "Fundación Grandmother's House is dedicated to providing a safe, stimulating, and loving environment where every child can develop fully. Through education, creative play, and community support, we strive to be the light for those in darkness."
  },
  "socialLinks": [
    {
      "id": "69c0a8d0d7df4316e5a0e7d9",
      "platform": "instagram",
      "url": "https://www.instagram.com/fundaciongrandmothershouse",
      "label": "Instagram"
    }
  ],
  "quickLinksTitle": {
    "es": "Enlaces rápidos",
    "en": "Quick links"
  },
  "servicesTitle": {
    "es": "Nuestros servicios",
    "en": "Our services"
  },
  "contactTitle": {
    "es": "Contáctanos",
    "en": "Get in touch"
  },
  "quickLinks": [
    {
      "id": "69c0a8d0d7df4316e5a0e7da",
      "label": {
        "es": "Quiénes Somos",
        "en": "About Us"
      },
      "link": "/quienes-somos"
    },
    {
      "id": "69c0a8d0d7df4316e5a0e7db",
      "label": {
        "es": "Actividades",
        "en": "Activities"
      },
      "link": "/actividades"
    },
    {
      "id": "footer-noticias-2026",
      "label": {
        "es": "Noticias",
        "en": "News"
      },
      "link": "/noticias"
    },
    {
      "id": "69c0a8d0d7df4316e5a0e7dc",
      "label": {
        "es": "Contacto",
        "en": "Contact"
      },
      "link": "/contacto"
    },
    {
      "id": "69c0a8d0d7df4316e5a0e7dd",
      "label": {
        "es": "Donar",
        "en": "Donate"
      },
      "link": "#"
    }
  ],
  "services": [
    {
      "id": "69c0a8d0d7df4316e5a0e7de",
      "label": {
        "es": "Apoyo educativo",
        "en": "Education support"
      },
      "link": "/actividades"
    },
    {
      "id": "69c0a8d0d7df4316e5a0e7df",
      "label": {
        "es": "Cuidado infantil",
        "en": "Child care"
      },
      "link": "/actividades"
    },
    {
      "id": "69c0a8d0d7df4316e5a0e7e0",
      "label": {
        "es": "Eventos comunitarios",
        "en": "Community events"
      },
      "link": "/actividades"
    },
    {
      "id": "69c0a8d0d7df4316e5a0e7e1",
      "label": {
        "es": "Entrega de juguetes",
        "en": "Toy drives"
      },
      "link": "/actividades"
    },
    {
      "id": "69c0a8d0d7df4316e5a0e7e2",
      "label": {
        "es": "Voluntariado",
        "en": "Volunteer"
      },
      "link": "/contacto"
    }
  ],
  "contactInfo": {
    "address": {
      "es": "Vía Boulevard Juan Dolio, John Hazim Subero, Calle el Tanque, SPM, RD",
      "en": "Vía Boulevard Juan Dolio, John Hazim Subero, Calle el Tanque, SPM, RD"
    },
    "addressLink": "https://maps.google.com/?q=Juan+Dolio+San+Pedro+de+Macoris+RD",
    "phone": "809-655-0290",
    "email": "grandmothershousedaycare@gmail.com"
  },
  "copyrightText": {
    "es": "Copyright © 2026 Fundación Grandmother's House. Todos los derechos reservados. RNC: 430-43228-8",
    "en": "Copyright © 2026 Fundación Grandmother's House. All rights reserved. RNC: 430-43228-8"
  },
  "legalLinks": [
    {
      "id": "69c0a8d0d7df4316e5a0e7e3",
      "label": {
        "es": "Términos y condiciones",
        "en": "Terms and conditions"
      },
      "link": "/terminos-y-condiciones"
    },
    {
      "id": "69c0a8d0d7df4316e5a0e7e4",
      "label": {
        "es": "Política de privacidad",
        "en": "Privacy policy"
      },
      "link": "/terminos-y-condiciones"
    }
  ]
}

