// Auto-generated by scripts/build-content.ts from .snapshot/*.json.
// Edit the source TypeScript directly when authoring new content via Claude-as-CMS.
// Do NOT commit raw snapshot JSON; this file IS the source of truth.

import type { Header } from '../schema'

export const header: Header = {
  "logo": null,
  "email": "grandmothershousedaycare@gmail.com",
  "phone": "809-655-0290",
  "donateButtonText": {
    "es": "Donar ahora",
    "en": "Donate now"
  },
  "socialLinks": [
    {
      "id": "69c0a8ced7df4316e5a0e7d2",
      "platform": "instagram",
      "url": "https://www.instagram.com/fundaciongrandmothershouse",
      "label": "Instagram"
    }
  ],
  "navigation": [
    {
      "id": "69c0a8ced7df4316e5a0e7d3",
      "label": {
        "es": "Inicio",
        "en": "Home"
      },
      "link": "/",
      "children": []
    },
    {
      "id": "69c0a8ced7df4316e5a0e7d6",
      "label": {
        "es": "Quiénes Somos",
        "en": "About Us"
      },
      "link": "/quienes-somos",
      "children": [
        {
          "id": "69c0a8ced7df4316e5a0e7d4",
          "label": {
            "es": "Misión",
            "en": "Mission"
          },
          "link": "/quienes-somos/mision"
        },
        {
          "id": "69c0a8ced7df4316e5a0e7d5",
          "label": {
            "es": "Visión",
            "en": "Vision"
          },
          "link": "/quienes-somos/vision"
        }
      ]
    },
    {
      "id": "69c0a8ced7df4316e5a0e7d7",
      "label": {
        "es": "Actividades",
        "en": "Activities"
      },
      "link": "/actividades",
      "children": []
    },
    {
      "id": "nav-noticias-2026",
      "label": {
        "es": "Noticias",
        "en": "News"
      },
      "link": "/noticias",
      "children": []
    },
    {
      "id": "69c0a8ced7df4316e5a0e7d8",
      "label": {
        "es": "Contacto",
        "en": "Contact"
      },
      "link": "/contacto",
      "children": []
    }
  ]
}

