// Auto-generated by scripts/build-content.ts from .snapshot/*.json.
// Edit the source TypeScript directly when authoring new content via Claude-as-CMS.
// Do NOT commit raw snapshot JSON; this file IS the source of truth.

import type { SiteSettings } from '../schema'

export const siteSettings: SiteSettings = {
  "siteName": "Fundación Grandmother's House",
  "favicon": null,
  "showHeroBanner": true,
  "showDifference": true,
  "showHelp": true,
  "showTestimonial": true,
  "showBlogPreview": true
}

